name: atithiverse
description: "SIH Project AtithiVerse - Smart Tourism Platform"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  http: ^1.1.0
  webview_flutter: ^4.4.4
  flutter_markdown: ^0.6.18+2

  # Camera & Image Processing (KEEP - These work!)
  camera: ^0.10.5+9
  image_picker: ^1.0.7

  # Location & Maps (KEEP - These work!)
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3

  # Storage & Data (KEEP - These work!)
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # UI Components (KEEP - These work!)
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1

  # Utilities (KEEP - These work!)
  url_launcher: ^6.2.5
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
